default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: 'postgres'
  password: 'postgres'
  host: 'localhost'
  port: 5432

development:
  <<: *default
  database: 'twitter_rails_development'

test:
  <<: *default
  database: twitter_rails_test

production:
  <<: *default
  database: twitter_rails_production
